version: '3.8'

services:
  ts_server:
    image: ts_server
    build: .
    restart: always
    volumes:
      - ./configs/ts_server.cfg:/root/ts_server/ts_server.cfg
      - ./models:/root/ts_server/models

  nginx:
    image: nginx:alpine-slim
    environment:
      BACKEND: ts_server:8080
    ports:
      - 127.0.0.1:9000:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.template
      - ./chatbox.html:/usr/share/nginx/html/index.html
    command:
      - /bin/sh
      - -c
      - envsubst '$$BACKEND' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf
        && exec nginx -g 'daemon off;'
